"""add language to posts

Revision ID: 080433e06a84
Revises: 23bd9cd87536
Create Date: 2020-07-31 23:32:06.397167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080433e06a84'
down_revision = '23bd9cd87536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
